[workspace]
resolver = "2"
members = [
    "dhkem",
    "frodo-kem",
    "ml-kem",
    "x-wing"
]

[profile.bench]
debug = true

[patch.crates-io]
ml-kem = { path = "./ml-kem" }

getrandom = { git = "https://github.com/rust-random/getrandom" }
