[workspace]
resolver = "2"
members = [
    "dhkem",
    "frodo-kem",
    "ml-kem",
    "module-lattice",
    "x-wing"
]

[profile.bench]
debug = true

[patch.crates-io]
ml-kem = { path = "./ml-kem" }
