[workspace]
resolver = "2"
members = [
    "dhkem",
    "frodo-kem",
    "ml-kem",
    "x-wing"
]

[profile.bench]
debug = true

[patch.crates-io]
ml-kem = { path = "./ml-kem" }

kem = { git = "https://github.com/RustCrypto/traits" }
sec1 = { git = "https://github.com/RustCrypto/formats" }
